name: Publish Release YAML

on:
  release:
    types: ['created']

jobs:
  publish-release-yaml:
    name: Publish Release YAML
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - uses: actions/checkout@v3
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: docker/setup-buildx-action@v2
    - id: meta
      uses: docker/metadata-action@v4
      with:
        images: ghcr.io/${{ github.repository }}/base
        flavor: |
          latest=true
    - uses: docker/build-push-action@v4
      with:
        push: true
        context: ./images/base
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
    - uses: imjasonh/setup-ko@v0.6
    - name: Generate and upload release.yaml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag=$(echo ${{ github.ref }} | cut -c11-)  # get tag name without tags/refs/ prefix.
        ko resolve -t ${tag} -f config/ > release.yaml
        gh release upload ${tag} release.yaml
